CREATE TABLE `TB_USER`
(
    `USER_ID` INT AUTO_INCREMENT PRIMARY KEY COMMENT '사용자 아이디',
    `USER_NAME` VARCHAR(20) NOT NULL COMMENT '사용자 이름',
    `NICKNAME` VARCHAR(20) NOT NULL COMMENT '닉네임',
    `PASSWORD` VARCHAR(30) NOT NULL COMMENT '비밀번호',
    `USER_BIRTHDAY` DATE NOT NULL COMMENT '사용자 생년월일',
    `GENDER` VARCHAR(1) NOT NULL COMMENT '성별(M-male/F-Female)',
    `AUTHORITY_CODE` VARCHAR(20) NOT NULL COMMENT '계정 활성화 여부(Y/N)',
    `USE_YN` VARCHAR(1) NOT NULL COMMENT 'Y-사용중 / N-휴먼계정'
) COMMENT = '사용자 테이블'
;