CREATE TABLE `TB_RESTAURANT`
(
    `RESTAURANT_ID` INT AUTO_INCREMENT PRIMARY KEY COMMENT '음식점 아이디',
    `RESTAURANT_NAME` VARCHAR(40) NOT NULL COMMENT '음식점 이름',
    `RESTAURANT_ADDRESS` VARCHAR(100) NOT NULL COMMENT '음식점 주소',
    `RESTAURANT_CATEGORY` VARCHAR(20) NOT NULL COMMENT '음식점 카테고리',
    `OPEN_STATUS` VARCHAR(10) NOT NULL COMMENT 'OPEN-영업중/CLOSED-휴접,폐업'
) COMMENT = '음식점 테이블'
;