CREATE TABLE `TB_MZ_LIST`
(
    `MZLIST_ID` INT AUTO_INCREMENT PRIMARY KEY COMMENT '맛집리스트 아이디',
    `USER_ID` INT NOT NULL COMMENT '사용자 아이디',
    `MZLIST_NAME` VARCHAR(40) NOT NULL COMMENT '맛집리스트 이름',
    `MZLIST_DESCRIPTION` VARCHAR(100) NOT NULL COMMENT '맛집리스트 설명',
    `MZLIST_ICON` VARCHAR(40) NOT NULL COMMENT '맛집리스트 ICON'
) COMMENT = '맛집 리스트 테이블'
;